version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=host
      - DB_NAME=name
      - DB_USER=user
      - DB_PASSWORD=password
      - TELEGRAM_BOT_TOKEN=bot-token
      - TELEGRAM_CHAT_ID=-100id
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=name
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data:
