version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=aws-db.ctbwu5xukfqx.eu-north-1.rds.amazonaws.com
      - DB_NAME=daraja_db
      - DB_USER=postgres
      - DB_PASSWORD=hasanboy1403
      - TELEGRAM_BOT_TOKEN=7319243662:AAFvtYJ-EfGB7-r2DYVTIr70QOhjD6gdjbw
      - TELEGRAM_CHAT_ID=-1002201681248
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=daraja_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hasanboy1403

volumes:
  postgres_data:
